replicaCount: 2

image:
  repository: jeevan725/pygame   # Replace with your DockerHub/GHCR repo
  tag: "v204"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
