apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pygame
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jeevanfrankline1988/Project.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
